### ISSUE TITLE
yarn update

### ISSUE THREAD

**Issue by mogya** [mogya/dengen_map#67]
for security alert lodash

**Comment by mogya** [comment]
after upgrading ruby and gems:

```
An error occurred while loading ./spec/controllers/landing_controller_spec.rb.
Failure/Error: status "open"

NoMethodError:
  undefined method 'status' in 'ee_datum' factory
# ./vendor/bundler/ruby/2.6.0/gems/factory_bot-5.0.2/lib/factory_bot/definition_proxy.rb:97:in `method_missing'
# ./spec/factories/ee_data.rb:4:in `block (2 levels) in <top (required)>'
```


and so on.

**Comment by mogya** [comment]
https://github.com/mogya/dengen_map/commit/f6d6268c5b2c0c0623bdb7038f68853c7f35b5e3

**Comment by mogya** [comment]
これFront側なので、そっちをビルドできないといけない。frontコンテナを作ったほうが良いか

**Comment by mogya** [comment]
#64,#65でいけるはず。だけど動作確認するためにはどっちにしてもビルド環境が必要

**Comment by mogya** [comment]
新しい環境で動くようになった。ただなんかネットワーク周りでおかしいらしく、アイコンが出ないので要調査
